[
   {
      "ID":"101",
      "PNAME":"Xbox Series X",
      "GNAME":"XboxSeriesXLogo.png",
      "COST":"500.00",
      "MSRP":"599.99",
      "QTYHAND":"5",
      "QTYBACK":"50",
      "DESC":"The next generation of Xbox gaming is now here in the most powerful game console in the world, Xbox Series X",
      "PRO":"40",
      "BRAND":"Microsoft"
   },
   {
      "ID":"102",
      "PNAME":"Xbox Series S",
      "GNAME":"XboxSeriesSLogo.jpg",
      "COST":"460.00",
      "MSRP":"379.99",
      "QTYHAND":"20",
      "QTYBACK":"15",
      "DESC":"Experience next generation gaming at an afforable price on the Xbox Series S",
      "PRO":"45",
      "BRAND":"Microsoft"
   },
   {
      "ID":"103",
      "PNAME":"Halo Infinite",
      "GNAME":"HaloInfiniteLogo.jpg",
      "COST":"60.00",
      "MSRP":"60.00",
      "QTYHAND":"50",
      "QTYBACK":"150",
      "DESC":"Halo Infinite is an upcoming first-person shooter game developed by 343 Industries and published by Xbox Game Studios for Windows, Xbox One, and Xbox Series X and Series S. The sixth main entry of the Halo series, and the sixteenth Halo game overall, it picks up the story of the Master Chief, following Guardians",
      "PRO":"40",
      "BRAND":"Microsoft"
   },
   {
      "ID":"104",
      "PNAME":"Forza Horizon 5",
      "GNAME":"ForzaHorizon5Logo.png",
      "COST":"60.00",
      "MSRP":"60.00",
      "QTYHAND":"50",
      "QTYBACK":"100",
      "DESC":"Forza Horizon 5 is an upcoming racing game developed by Playground Games and published by Xbox Game Studios. It will be the fifth Forza Horizon title and twelfth main instalment in the Forza series. The game is set in a fictionalised representation of Mexico",
      "PRO":"14",
      "BRAND":"Microsoft"
   },
   {
      "ID":"105",
      "PNAME":"Fable",
      "GNAME":"FableLogo.jpg",
      "COST":"60.00",
      "MSRP":"60.00",
      "QTYHAND":"50",
      "QTYBACK":"80",
      "DESC":"Fable returns in the reboot of the classic Xbox franchise coming exclusively to Xbox and PC",
      "PRO":"14",
      "BRAND":"Microsoft"
   },
   {
      "ID":"201",
      "PNAME":"PS5",
      "GNAME":"PS5Logo.jpg",
      "COST":"450.00",
      "MSRP":"629.99",
      "QTYHAND":"3",
      "QTYBACK":"20",
      "DESC":"The next generation of Sony PlayStatio is here on the PS5",
      "PRO":"20",
      "BRAND":"Sony"
   },
   {
      "ID":"202",
      "PNAME":"PS5 Digital",
      "GNAME":"PS5DigitalLogo.jpg",
      "COST":"450.00",
      "MSRP":"499.99",
      "QTYHAND":"10",
      "QTYBACK":"22",
      "DESC":"Play next gen PS5 games at a lower cost with the digital only PS5 console",
      "PRO":"22",
      "BRAND":"Sony"
   },
   {
      "ID":"203",
      "PNAME":"God of War Ragnarok",
      "GNAME":"GodOfWarRagnarokLogo.png",
      "COST":"70.00",
      "MSRP":"70.00",
      "QTYHAND":"50",
      "QTYBACK":"100",
      "DESC":"The untitled God of War sequel is an action-adventure game currently in development by Santa Monica Studio and will be published by Sony Interactive Entertainment. It is scheduled to be released in 2022 for the PlayStation 4 and PlayStat0ion 5",
      "PRO":"25",
      "BRAND":"Sony"
   },
   {
      "ID":"204",
      "PNAME":"Horizon Forbidden West",
      "GNAME":"HorizonForbiddenWestLogo.jpg",
      "COST":"70.00",
      "MSRP":"70.00",
      "QTYHAND":"40",
      "QTYBACK":"80",
      "DESC":"Horizon Forbidden West is an upcoming action role-playing game developed by Guerrilla Games and published by Sony Interactive Entertainment. It is set to be released in 2021 for the PlayStation 4 and PlayStation 5. A sequel to Horizon Zero Dawn, it features an open world in a post-apocalyptic western United States",
      "PRO":"15",
      "BRAND":"Sony"
   },
   {
      "ID":"205",
      "PNAME":"Ratchet & Clank: Rift Apart",
      "GNAME":"RachetAndClankRiftApartLogo.jpg",
      "COST":"70.00",
      "MSRP":"70.00",
      "QTYHAND":"20",
      "QTYBACK":"40",
      "DESC":"Ratchet & Clank: Rift Apart is a 2021 third-person shooter platform game developed by Insomniac Games and published by Sony Interactive Entertainment for the PlayStation 5. It is the sixteenth installment in the Ratchet & Clank series. The game takes place following the events of Ratchet & Clank: Into the Nexus.",
      "PRO":"22",
      "BRAND":"Sony"
   },
   {
      "ID":"301",
      "PNAME":"Nintendo Switch",
      "GNAME":"NintendoSwitchLogo.jpg",
      "COST":"400.00",
      "MSRP":"399.99",
      "QTYHAND":"20",
      "QTYBACK":"60",
      "DESC":"The Nintendo Switch is a hybrid video game console, consisting of a console unit, a dock, and two Joy-Con controllers. Although it is a hybrid console, Nintendo classifies it as 'a home console that you can take with you on the go'",
      "PRO":"36",
      "BRAND":"Nintendo"
   },
   {
      "ID":"302",
      "PNAME":"Nintendo Switch Lite",
      "GNAME":"NintendoSwitchLiteLogo.jpg",
      "COST":"280.00",
      "MSRP":"259.99",
      "QTYHAND":"30",
      "QTYBACK":"15",
      "DESC":"The Nintendo Switch Lite is designed specifically for handheld play so you can jump into your favorite games wherever you happen to be.",
      "PRO":"41",
      "BRAND":"Nintendo"
   },
   {
      "ID":"303",
      "PNAME":"Zelda Breath of the Wild 2",
      "GNAME":"ZeldaBreathOfTheWildLogo.jpg",
      "COST":"60.00",
      "MSRP":"60.00",
      "QTYHAND":"50",
      "QTYBACK":"100",
      "DESC":"An untitled sequel to the 2017 action-adventure game The Legend of Zelda: Breath of the Wild is in development by Nintendo. The sequel is part of The Legend of Zelda series and is currently set to be released in 2022 for the Nintendo Switch",
      "PRO":"31",
      "BRAND":"Nintendo"
   },
   {
      "ID":"304",
      "PNAME":"Pokemon Legends: Arceus",
      "GNAME":"PokemonLegendsArceusLogo.png",
      "COST":"60.00",
      "MSRP":"60.00",
      "QTYHAND":"40",
      "QTYBACK":"90",
      "DESC":"Pokémon Legends: Arceus is an upcoming 2022 action role-playing game developed by Game Freak and published by Nintendo and The Pokémon Company for the Nintendo Switch",
      "PRO":"35",
      "BRAND":"Nintendo"
   },
   {
      "ID":"305",
      "PNAME":"Super Mario 3D All-Stars",
      "GNAME":"SuperMario3DAllStarsLogo.jpg",
      "COST":"60.00",
      "MSRP":"60.00",
      "QTYHAND":"8",
      "QTYBACK":"0",
      "DESC":"Super Mario 3D All-Stars is a 2020 compilation of platform games for the Nintendo Switch. It commemorates the 35th anniversary of Nintendos Super Mario franchise, with high-definition ports of Super Mario 64, Super Mario Sunshine, and Super Mario Galaxy",
      "PRO":"27",
      "BRAND":"Nintendo"
   }
]
