[
   {
      "CAL":"Xbox Series X",
      "FAT":"XboxSeriesXLogo",
      "CHOL":"500.00",
      "SALT":"599.99",
      "CARB":"5",
      "FBR":"50",
      "ITEM":"temp",
      "PRO":"40",
      "CATEGORY":"Microsoft"
   },
   {
      "CAL":"Xbox Series S",
      "FAT":"XboxSeriesSLogo",
      "CHOL":"460.00",
      "SALT":"379.99",
      "CARB":"20",
      "FBR":"15",
      "ITEM":"temp",
      "PRO":"45",
      "CATEGORY":"Microsoft"
   },
   {
      "CAL":"Halo Infinite",
      "FAT":"HaloInfiniteLogo",
      "CHOL":"60.00",
      "SALT":"60.00",
      "CARB":"50",
      "FBR":"150",
      "ITEM":"temp",
      "PRO":"40",
      "CATEGORY":"Microsoft"
   },
   {
      "CAL":"Forza Horizon 5",
      "FAT":"ForzaHorizon5Logo",
      "CHOL":"60.00",
      "SALT":"60.00",
      "CARB":"50",
      "FBR":"100",
      "ITEM":"temp",
      "PRO":"14",
      "CATEGORY":"Microsoft"
   },
   {
      "CAL":"Fable",
      "FAT":"FableLogo",
      "CHOL":"60.00",
      "SALT":"60.00",
      "CARB":"50",
      "FBR":"80",
      "ITEM":"temp",
      "PRO":"14",
      "CATEGORY":"Microsoft"
   },
   {
      "CAL":"PS5",
      "FAT":"PS5Logo",
      "CHOL":"450.00",
      "SALT":"629.99",
      "CARB":"3",
      "FBR":"20",
      "ITEM":"temp",
      "PRO":"20",
      "CATEGORY":"Sony"
   },
   {
      "CAL":"PS5 Digital",
      "FAT":"PS5DigitalLogo",
      "CHOL":"450.00",
      "SALT":"499.99",
      "CARB":"10",
      "FBR":"22",
      "ITEM":"temp",
      "PRO":"22",
      "CATEGORY":"Sony"
   },
   {
      "CAL":"God of War Ragnarok",
      "FAT":"GodOfWarRagnarokLogo",
      "CHOL":"70.00",
      "SALT":"70.00",
      "CARB":"50",
      "FBR":"100",
      "ITEM":"temp",
      "PRO":"25",
      "CATEGORY":"Sony"
   },
   {
      "CAL":"Horizon Forbidden West",
      "FAT":"HorizonForbiddenWestLogo",
      "CHOL":"70.00",
      "SALT":"70.00",
      "CARB":"40",
      "FBR":"80",
      "ITEM":"temp",
      "PRO":"15",
      "CATEGORY":"Sony"
   },
   {
      "CAL":"Ratchet & Clank: Rift Apart",
      "FAT":"RachetAndClankRiftApartLogo",
      "CHOL":"70.00",
      "SALT":"70.00",
      "CARB":"20",
      "FBR":"40",
      "ITEM":"temp",
      "PRO":"22",
      "CATEGORY":"Sony"
   },
   {
      "CAL":"Nintendo Switch",
      "FAT":"NintendoSwitchLogo",
      "CHOL":"400.00",
      "SALT":"399.99",
      "CARB":"20",
      "FBR":"60",
      "ITEM":"temp",
      "PRO":"36",
      "CATEGORY":"Nintendo"
   },
   {
      "CAL":"Nintendo Switch Lite",
      "FAT":"NintendoSwitchLiteLogo",
      "CHOL":"280.00",
      "SALT":"259.99",
      "CARB":"30",
      "FBR":"15",
      "ITEM":"temp",
      "PRO":"41",
      "CATEGORY":"Nintendo"
   },
   {
      "CAL":"Zelda Breath of the Wild 2",
      "FAT":"ZeldaBreathOfTheWildLogo",
      "CHOL":"60.00",
      "SALT":"60.00",
      "CARB":"50",
      "FBR":"100",
      "ITEM":"temp",
      "PRO":"31",
      "CATEGORY":"Nintendo"
   },
   {
      "CAL":"Pokemon Legends: Arceus",
      "FAT":"PokemonLegendsArcuesLogo",
      "CHOL":"60.00",
      "SALT":"60.00",
      "CARB":"40",
      "FBR":"90",
      "ITEM":"temp",
      "PRO":"35",
      "CATEGORY":"Nintendo"
   },
   {
      "CAL":"Super Mario 3D All-Stars",
      "FAT":"SuperMario3DAllStarsLogo",
      "CHOL":"60.00",
      "SALT":"60.00",
      "CARB":"8",
      "FBR":"0",
      "ITEM":"temp",
      "PRO":"27",
      "CATEGORY":"Nintendo"
   }
]
